# Generated by Django 4.1.1 on 2022-09-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220904_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
